baseurl = "/"
publishDir = "public"
title = "orrymr.com"
author = "Orry Messer"
canonifyurls = true
languagecode = "en"
theme = "hugo-tanka"

googleAnalytics = ""
disqusShortname = ""
disable_mathjax = false

pygmentsstyle      = "vs"
pygmentscodefences = true

ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[params]
  sitename = "orrymr.com"

[[menu.main]]
    name = "Home"
    url = "http://orrymr.com"
    weight = 1
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/orrymr"
    weight = 2
[[menu.main]]
    name = "Music"
    url = "#"
    weight = 3
[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/orrymr"
    weight = 4
[[menu.main]]
    name = "About"
    url = "#"
    weight = 4
[[menu.main]]
    name = "RSS"
    url = "/index.xml"
    weight = 5
